function Hd = mytheta
%MYTHETA Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.6 and the Signal Processing Toolbox 6.9.
%
% Generated on: 31-May-2011 13:51:44
%

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 25000;  % Sampling Frequency

N   = 4;   % Order
Fc1 = 4;   % First Cutoff Frequency
Fc2 = 10;  % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass('N,Fc1,Fc2', N, Fc1, Fc2, Fs);
Hd = design(h, 'butter');

% [EOF]
